### ISSUE TITLE
Include adaguc config file that is using ADAGUC_DB environment variable

### ISSUE THREAD

**Issue by murb** [KNMI/adaguc-server#138]
ADAGUC_DB is suggested in the docker-compose example; but the update database call does not receive a config file that useses ADAGUC_DB variable and instead tries to connect to a database on localhost. Sadly the adaguc.docker.yml uses sqlite, which doesn't work with all datasets the last time I tried :)

**Comment by maartenplieger** [comment]
Hi Maarten Brouwers,

If you start adaguc-server with docker-compose it does use the ADAGUC_DB and it does use PostGres.

Happy to have a call with you if needed.

Cheers,
Maarten
________________________________________
Van: Maarten Brouwers <notifications@github.com>
Verzonden: dinsdag 28 juli 2020 16:45:04
Aan: KNMI/adaguc-server
CC: Subscribed
Onderwerp: [KNMI/adaguc-server] Include adaguc config file that is using ADAGUC_DB environment variable (#138)

ADAGUC_DB is suggested in the docker-compose example; but the update database call does not receive a config file that useses ADAGUC_DB variable and instead tries to connect to a database on localhost. Sadly the adaguc.docker.yml uses sqlite, which doesn't work with all datasets the last time I tried :)
