### ISSUE TITLE
DataPostProc issue with time series data

### ISSUE THREAD

**Issue by kktuax** [KNMI/adaguc-server#155]
We are facing issues plotting data stored on a [time series NetCDF](https://github.com/KNMI/adaguc-server/files/5920234/tasmaxhwdmax_mmm_rcp45__year_1971_2100_clim.nc.zip) when using DataPostProc on the layer definition.

Adaguc version: 2.5.4.

We use DataPostProc to override the declared units in the NetCDF.

This is how we are setting up the process environment:

```
ADAGUC_CONFIG=/tmp/adagucMgrCfg/configuration.xml
ADAGUC_TMP=/tmp
ADAGUC_LOGFILE=/tmp/adaguctmp/adaguc-1362314522471699936.log
HOME=/tmp
QUERY_STRING=service=WMS&request=GetMap&version=1.1.1&layers=tasmaxhwdmax&format=png&transparent=true&dataset=AEMET-rcp45&crs=EPSG%3A4326&width=1600&height=830&srs=EPSG%3A3857&bbox=-1335507.7581985998%2C4474929.383927359%2C621280.1659019126%2C5490013.1195545
CONTENT_TYPE=null
ADAGUC_ONLINERESOURCE=http://localhost:8080/wms?
ADAGUC_PATH=/adaguc/adaguc-server-master
ADAGUC_ERRORFILE=/tmp/adaguc-server.errlog
ADAGUC_FONT=/adaguc/adaguc-server-master/data/fonts/Roboto-Light.ttf
ADAGUC_DATARESTRICTION=FALSE
ADAGUC_DB=host=db port=5432 user=user password=changeme dbname=adaguc
```

This is the execution log we get before the process crashes:

> [D:000:pid113: /adaguc/adaguc-server-master/adagucserverEC/CAutoResource.cpp, 81 in CAutoResource] 2021-02-03T09:19:03Z Found dataset /tmp/adagucMgrCfg/AEMET-rcp45.xml
> [D:001:pid113: /adaguc/adaguc-server-master/adagucserverEC/CRequest.cpp, 818 in CRequest] 2021-02-03T09:19:03Z WMS GETMAP (0) tasmaxhwdmax
> [D:002:pid113: /adaguc/adaguc-server-master/adagucserverEC/CRequest.cpp, 1453 in CRequest] 2021-02-03T09:19:03Z Using maxquerylimit 365
> [D:003:pid113: /adaguc/adaguc-server-master/adagucserverEC/CDataReader.cpp, 765 in CDataReader] 2021-02-03T09:19:03Z Working on [/tmp/tasmaxhwdmax_mmm_rcp45__year_1971_2100_clim.nc]
> [D:004:pid113: /adaguc/adaguc-server-master/adagucserverEC/CConvertADAGUCPoint.cpp, 171 in CConvertADAGUCPoint] 2021-02-03T09:19:04Z Using CConvertADAGUCPoint.h
> [D:005:pid113: /adaguc/adaguc-server-master/adagucserverEC/CDataReader.cpp, 582 in CDataReader] 2021-02-03T09:19:04Z Assuming that for variable tasmaxhwdmax the x dim equals x and the y dim equals y based on their position and name.
> [D:006:pid113: /adaguc/adaguc-server-master/adagucserverEC/CDataReader.cpp, 609 in CDataReader] 2021-02-03T09:19:04Z Using variable x as X variable and variable y as Y variable.
> [D:007:pid113: /adaguc/adaguc-server-master/adagucserverEC/CDataReader.cpp, 618 in CDataReader] 2021-02-03T09:19:04Z In level 2 compatibility mode, using a default stride of 1, not considering RenderSettings.
> [D:008:pid113: /adaguc/adaguc-server-master/adagucserverEC/CDataPostProcessor.cpp, 51 in CDPPAXplusB] 2021-02-03T09:19:04Z Applying ax+b
> [D:009:pid113: /adaguc/adaguc-server-master/adagucserverEC/CImageDataWriter.cpp, 3394 in CImageDataWriter] 2021-02-03T09:19:04Z Creating 8 bit png with alpha
> [D:010:pid113: /adaguc/adaguc-server-master/adagucserverEC/CDrawImage.cpp, 216 in CDrawImage] 2021-02-03T09:19:04Z printImagePng8 CAIRO
> [D:011:pid113: /adaguc/adaguc-server-master/adagucserverEC/CCairoPlotter.cpp, 899 in CCairoPlotter] 2021-02-03T09:19:04Z Number of quantized colors: 2
> [D:012:pid113: /adaguc/adaguc-server-master/adagucserverEC/CCairoPlotter.cpp, 920 in CCairoPlotter] 2021-02-03T09:19:04Z Num alpha colors: 2

And the relevant configuration:

```xml
<Configuration>
   <Style name="number_of_days">
      <Legend fixed="true">temperature</Legend>
      <RenderMethod>nearest</RenderMethod>
      <NameMapping name="nearest" title="Número de días" abstract="Número de días"/>
   </Style>
   <Style name="number_of_days_point">
      <Legend fixed="true">temperature</Legend>
      <RenderMethod>nearest</RenderMethod>
      <Point plotstationid="false" pointstyle="point" discradius="8" textradius="0" dot="false" fontsize="0" textformat=" " textcolor="#000000"/>
      <RenderMethod>point</RenderMethod>
      <NameMapping name="point" title="Número de días" abstract="Número de días"/>
   </Style>
   <Layer type="database">
      <Name>tasmaxhwdmax</Name>
      <FilePath>/tmp/tasmaxhwdmax_mmm_rcp45__year_1971_2100_clim.nc</FilePath>
      <DataPostProc algorithm="ax+b" a="1.0" b="0.0" units="Dias" />
      <Variable>tasmaxhwdmax</Variable>
      <Styles>number_of_days,number_of_days_point</Styles>
      <Min>5.0</Min>
      <Max>25.0</Max>
   </Layer>
</Configuration>
```

**Comment by maartenplieger** [comment]
Thanks Max. Checking these now.

**Comment by danielsms** [comment]
Thanks Maarten! I take the opportunity to ask you if there is any alternative method for overriding the variable units attribute. We've tried using the ```<StandardNames/>``` tag in the ```Layer``` definition but it does not work. This is why Max is using a dummy ```<DataPostProc/>``` operation as a trick.

**Comment by maartenplieger** [comment]
There is, by using an NCML file: https://github.com/KNMI/adaguc-server/blob/master/doc/ncml.md

Not sure if it resolves your issue though :).

See NCML details here: https://www.unidata.ucar.edu/software/netcdf-java/v4.6/ncml/Cookbook.html

**Comment by maartenplieger** [comment]
This dataset configuration file:
```xml

<Configuration>

   <Style name="number_of_days">
      <Legend fixed="true">temperature</Legend>
      <RenderMethod>nearest</RenderMethod>
      <NameMapping name="nearest" title="Número de días" abstract="Número de días"/>
   </Style>
   <Style name="number_of_days_point">
      <Legend fixed="true">temperature</Legend>
      <RenderMethod>nearest</RenderMethod>
      <Point plotstationid="false" pointstyle="point" discradius="8" textradius="0" dot="false" fontsize="0" textformat=" " textcolor="#000000"/>
      <RenderMethod>point</RenderMethod>
      <NameMapping name="point" title="Número de días" abstract="Número de días"/>
   </Style>
   <Layer type="database">
      <Name>tasmaxhwdmax</Name>
      <FilePath ncml="{ADAGUC_DATASET_DIR}/155.ncml">{ADAGUC_DATA_DIR}/155/tasmaxhwdmax_mmm_rcp45__year_1971_2100_clim.nc</FilePath>
      <!--<DataPostProc algorithm="ax+b" a="1.0" b="0.0" units="Dias" />-->
      <Variable>tasmaxhwdmax</Variable>
      <Styles>number_of_days,number_of_days_point</Styles>
      <Min>5.0</Min>
      <Max>25.0</Max>
   </Layer>
</Configuration>
```
with this NCML file (in the datasets folder):
```xml
<?xml version="1.0" encoding="UTF-8"?>
<netcdf xmlns="http://www.unidata.ucar.edu/namespaces/netcdf/ncml-2.2">
  <variable name="tasmaxhwdmax">
    <attribute name="units" type="String" value="Dias" />
  </variable>
</netcdf>
```

Adjusts the units. I think this is what you want to achieve, right?

**Comment by danielsms** [comment]
Hi Marteen, yes, using NCMLs is a good option for us. Thank you!

**Comment by maartenplieger** [comment]
Data post processor is now not possible when using a format convert, like the one for timeseries data.
