### ISSUE TITLE
timeSeries NetCDF not detecting first dimension

### ISSUE THREAD

**Issue by kktuax** [KNMI/adaguc-server#156]
We have a [multi-dimensional timeSeries NetCDF](https://github.com/KNMI/adaguc-server/files/5920267/tasmax_multimodel_rcp45_1971_2100_clim.nc.zip). The layer depends on three string-valued dimensions (member, time_filter and period):

```
	float tasmax(member, time_filter, period, station) ;
		tasmax:_FillValue = NaNf ;
		tasmax:long_name = "Daily Maximum Near-Surface Air Temperature" ;
		tasmax:standard_name = "air_temperature" ;
		tasmax:units = "Celsius" ;
		tasmax:coordinates = "lat lon projection" ;
```

This is the layer definition:		

```xml
<Configuration>
    <Layer type="database">
        <Name>tasmax</Name>
        <FilePath>/temp/tasmax_multimodel_rcp45_1971_2100_clim.nc</FilePath>
        <Variable>tasmax</Variable>
        <Styles>temperature,temperature_point</Styles>
        <Min>5.0</Min>
        <Max>45.0</Max>
    </Layer>
</Configuration>
```

After a successful on DB update, the first dimension is not auto-detected:

> [D:003:pid67: /adaguc/adaguc-server-master/adagucserverEC/CDBFileScanner.cpp, 959 in CDBFileScanner] *** Starting update layer 'tasmax' ***
> [D:004:pid67: /adaguc/adaguc-server-master/adagucserverEC/CDBFileScanner.cpp, 961 in CDBFileScanner] Using path [/temp/tasmax_multimodel_rcp45_1971_2100_clim.nc], filter [] and tailpath []
> [D:005:pid67: /adaguc/adaguc-server-master/adagucserverEC/CConvertADAGUCPoint.cpp, 171 in CConvertADAGUCPoint] Using CConvertADAGUCPoint.h
> [D:006:pid67: /adaguc/adaguc-server-master/adagucserverEC/CAutoConfigure.cpp, 529 in CAutoConfigure] Loading header [/temp/tasmax_multimodel_rcp45_1971_2100_clim.nc]
> [D:007:pid67: /adaguc/adaguc-server-master/adagucserverEC/CDataReader.cpp, 1346 in CDataReader] Dimension time_filter with standard_name [time_filter] is a normal dimension
> [D:008:pid67: /adaguc/adaguc-server-master/adagucserverEC/CDataReader.cpp, 1346 in CDataReader] Dimension period with standard_name [period] is a normal dimension
> [D:009:pid67: /adaguc/adaguc-server-master/adagucserverEC/CDBFileScanner.cpp, 118 in CDBFileScanner] Checking dim [time_filter]
> [D:010:pid67: /adaguc/adaguc-server-master/adagucserverEC/CDataReader.cpp, 1346 in CDataReader] Dimension time_filter with standard_name [time_filter] is a normal dimension
> [D:011:pid67: /adaguc/adaguc-server-master/adagucserverEC/CDBAdapterPostgreSQL.cpp, 876 in CDBAdapterPostgreSQL] New table created: Set indexes
> [D:012:pid67: /adaguc/adaguc-server-master/adagucserverEC/CDBFileScanner.cpp, 118 in CDBFileScanner] Checking dim [period]
> [D:013:pid67: /adaguc/adaguc-server-master/adagucserverEC/CDataReader.cpp, 1346 in CDataReader] Dimension period with standard_name [period] is a normal dimension
> [D:014:pid67: /adaguc/adaguc-server-master/adagucserverEC/CDBAdapterPostgreSQL.cpp, 876 in CDBAdapterPostgreSQL] New table created: Set indexes
> [D:015:pid67: /adaguc/adaguc-server-master/adagucserverEC/CDataReader.cpp, 1346 in CDataReader] Dimension time_filter with standard_name [time_filter] is a normal dimension
> [D:016:pid67: /adaguc/adaguc-server-master/adagucserverEC/CDBFileScanner.cpp, 367 in CDBFileScanner] Found dimension 0 with name time_filter of type 1, istimedim: [0]
> [D:017:pid67: /adaguc/adaguc-server-master/adagucserverEC/CDBFileScanner.cpp, 389 in CDBFileScanner] Marking table done for dim 'time_filter' with table 't20210203t165310141_wqvhuc03rg1dz6m5yaz'.
> [D:018:pid67: /adaguc/adaguc-server-master/adagucserverEC/CDataReader.cpp, 1346 in CDataReader] Dimension period with standard_name [period] is a normal dimension
> [D:019:pid67: /adaguc/adaguc-server-master/adagucserverEC/CDBFileScanner.cpp, 367 in CDBFileScanner] Found dimension 1 with name period of type 1, istimedim: [0]
> [D:020:pid67: /adaguc/adaguc-server-master/adagucserverEC/CDBFileScanner.cpp, 389 in CDBFileScanner] Marking table done for dim 'period' with table 't20210203t165310153_ljxhrl2p95peyapv2pnq'.
> [D:021:pid67: /adaguc/adaguc-server-master/adagucserverEC/CDBFileScanner.cpp, 396 in CDBFileScanner] Found 1 files Adding: 0/1 (time_filter, period)     /temp/tasmax_multimodel_rcp45_1971_2100_clim.nc
> [D:023:pid67: /adaguc/adaguc-server-master/adagucserverEC/CDataReader.cpp, 582 in CDataReader] Assuming that for variable tasmax the x dim equals x and the y dim equals y based on their position and name.
> [D:024:pid67: /adaguc/adaguc-server-master/adagucserverEC/CDataReader.cpp, 609 in CDataReader] Using variable x as X variable and variable y as Y variable.
> [D:025:pid67: /adaguc/adaguc-server-master/adagucserverEC/CDataReader.cpp, 618 in CDataReader] In level 2 compatibility mode, using a default stride of 1, not considering RenderSettings.
> [D:026:pid67: /adaguc/adaguc-server-master/adagucserverEC/CDataReader.cpp, 582 in CDataReader] Assuming that for variable tasmax the x dim equals x and the y dim equals y based on their position and name.
> [D:027:pid67: /adaguc/adaguc-server-master/adagucserverEC/CDataReader.cpp, 609 in CDataReader] Using variable x as X variable and variable y as Y variable.
> [D:028:pid67: /adaguc/adaguc-server-master/adagucserverEC/CDataReader.cpp, 618 in CDataReader] In level 2 compatibility mode, using a default stride of 1, not considering RenderSettings.
> [D:029:pid67: /adaguc/adaguc-server-master/adagucserverEC/CDBFileScanner.cpp, 1048 in CDBFileScanner] *** Finished update layer 'tasmax' ***

As a consequence only two dimensions are stored in the DB and advertised in GetCapabilities:

```xml
<Dimension name="time_filter" units="ISO8601" default="year" multipleValues="1" nearestValue="0" current="1">
	Apr,Aug,Dec,DJF,Feb,Jan,JJA,Jul,Jun,MAM,Mar,May,Nov,Oct,Sep,SON,year
</Dimension>
<Dimension name="period" units="NA" default="far_future" multipleValues="1" nearestValue="0">reference,near_future,medium_future,far_future</Dimension>
```

The adaguc version is: 2.5.4.

**Comment by maartenplieger** [comment]
Maybe this solves it? https://github.com/KNMI/adaguc-server/pull/157

**Comment by kktuax** [comment]
Thank you so much Maarten! Now it detects all three dimensions.
