### ISSUE TITLE
Contour rendering has more labels and fewer lines than in the past

### ISSUE THREAD

**Issue by kxfeldhus** [KNMI/adaguc-server#173]
I recently upgraded to the most recent version of Adaguc Server from the version in late 2019.  One of the differences I noticed was with the rendering of contours.  Previously it appears as though labels were being more evenly spaced across the whole domain.  Now it appears as though they are being spaced evenly along a single contour line, but there is crowding in dense areas.  It also appears as though there are fewer contour lines.

I've attached the files that are the result of the same backing data and configuration.  I did play with the `scalecontours` setting but that did not have my desired effect of thinning out the labels but leaving the lines.

![new](https://user-images.githubusercontent.com/168697/132388365-dcea93cd-0044-4ec5-926c-df6bbf75050f.png)
![old](https://user-images.githubusercontent.com/168697/132388371-09d8e423-fe6d-47b8-8d17-d6fe67d88b74.png)

Please let me know if there is an existing feature or config that I can use to keep the behavior the same.

If there isn't, I'd be happy to contribute to the project by adding that functionality.

**Comment by maartenplieger** [comment]
Hi!

There is currently no way to configure how the contourlines render and how the text in those contourlines should be placed.

The text is rendered here: https://github.com/KNMI/adaguc-server/blob/master/adagucserverEC/CImgWarpBilinear.cpp#L993 and I think the issue has to do with the textTooClose function at https://github.com/KNMI/adaguc-server/blob/master/adagucserverEC/CImgWarpBilinear.cpp#L815

**Comment by kxfeldhus** [comment]
Thanks for your reply!  That was what I was suspecting as well.  I'll take a look and see if I can come up with some ideas.
