### ISSUE TITLE
Features disappearing on certain BBOX 

### ISSUE THREAD

**Issue by kktuax** [KNMI/adaguc-server#207]
I'm trying to plot a very simple rectangular feature in two tiles, however, it only gets printed on one of the two tiles.

```json
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "geometry": {
        "type": "MultiPolygon",
        "coordinates": [[[
           [-9.5, 41.5],[-1, 41.5],[-1, 44],[-9.5, 44],[-9.5, 41.5]
        ]]]
      },
      "id": "cantabrican"
    }
  ]
}
```

![image](https://user-images.githubusercontent.com/3185625/156573894-6acd828e-cc5e-4279-ab56-17081b009b3b.png)

The "right" tile gets correctly printed with either [mercator](http://localhost:8080/wms?dataset=mask-cantabrian&service=WMS&request=GetMap&layers=domain-mask&transparent=true&version=1.1.1&width=1024&height=1024&srs=EPSG%3A3857&bbox=-626172.1357121639%2C5009377.085697314%2C0%2C5635549.221409476&format=image%2Fpng) or [CRS84](http://localhost:8080/wms?dataset=mask-cantabrian&service=WMS&request=GetMap&layers=domain-mask&transparent=true&version=1.1.1&width=1024&height=1024&srs=CRS%3A84&bbox=-5.37%2C40.58%2C0%2C45.5&format=image%2Fpng) bbox

Bbox coords

| Mercator | WGS84 |
| -- | --- |
| -626172.1357121639 |	-5°37'30" |
| 5009377.085697314 | 40°58'47.633" |
| 0 				|	0 |
| 5635549.221409476 | 	45°5'20.528" |

![image](https://user-images.githubusercontent.com/3185625/156574842-7da5073f-4eaf-4587-bc2a-a9831fff536c.png)

However the "left" part of the feature is not showing up either with [mercator](http://localhost:8080/wms?dataset=mask-cantabrian&service=WMS&request=GetMap&layers=domain-mask&transparent=true&version=1.1.1&width=1024&height=1024&srs=EPSG%3A3857&bbox=-1252344.2714243277%2C5009377.085697314%2C-626172.1357121639%2C5635549.221409476&format=image%2Fpng) or [CRS84](http://localhost:8080/wms?dataset=mask-cantabrian&service=WMS&request=GetMap&layers=domain-mask&transparent=true&version=1.1.1&width=1024&height=1024&srs=CRS%3A84&bbox=-11.15%2C40.58%2C-5.37%2C45.5&format=image%2Fpng) bbox:

| Mercator | WGS84 |
| -- | --- |
| -1252344.2714243277 |	-11°15'0" |
| 5009377.085697314 | 40°58'47.633" |
| -626172.1357121639 				|	-5°37'30" |
| 5635549.221409476 | 		45°5'20.528" |

![image](https://user-images.githubusercontent.com/3185625/156574982-21efa811-0fa5-4735-85a3-f2dac615d799.png)

This is how I've configured the layer and relevant style:

```xml
<Configuration>
  <Layer type="database">
    <Name>domain-mask</Name>
    <FilePath>/tmp/domains/cantabrian-14679283950060533581.json</FilePath>
    <Variable>features</Variable>
    <Styles>mask-cantabrian</Styles>
  </Layer>
</Configuration>
```
```xml
<Configuration>
  <Style name="mask-cantabrian">
    <Legend fixed="true">baselayer</Legend>
    <RenderMethod>nearest</RenderMethod>
    <NameMapping name="nearest" title="mask" />
    <FeatureInterval match=".*" matchid="id" bgcolor="#00000000" fillcolor="#FFFFFFFF" label="Other" />
  </Style>
</Configuration>
```

I've tried comparing the logs in the two cases but I don't find anything relevant. Any idea what might be going on?

Many thanks in advance

**Comment by ernstdevreede** [comment]
I've tried to reproduce your problem, but I don't get the same results as you:  I see the black area in both tiles correctly.
Is that what you expect to see: a black area in both tiles?
What version of adaguc-server where you using? (You can see this in the getCapablities output)

**Comment by kktuax** [comment]
Thanks for checking this out. Yes, there should be black area in both tiles.

I'm using ADAGUCServer version 2.6.0, of Nov 16 2021 14:19:30. I see there is already 2.6.8, I'll try to reproduce the issue with the latest version and come back to you.

**Comment by kktuax** [comment]
I've tried with the 2.6.8 tag but I'm afraid the problem still exists in my case (ADAGUCServer version 2.6.8, of Feb 8 2022 07:55:01). Are you also on 2.6.8?

**Comment by kktuax** [comment]
In case it helps: the problem only appears plotting features. Using a [netcdf with data in the same bbox](https://github.com/KNMI/adaguc-server/files/8184950/cantabrian-14433215546057023922.nc.zip) both tiles work fine:

```xml
<Configuration>
	<Layer type="database">
		<Name>domain-mask</Name>
		<FilePath>/tmp/domains/cantabrian-14433215546057023922.nc</FilePath>
		<Variable>features</Variable>
		<Styles>mask-cantabrian</Styles>
	</Layer>
</Configuration>
```

```xml
<Configuration>
	<Style name="mask-cantabrian">
		<Legend fixed="true">baselayer</Legend>
		<RenderMethod>nearest</RenderMethod>
		<NameMapping name="nearest" title="mask" />
	</Style>
</Configuration>
```

**Comment by maartenplieger** [comment]
Hi ,

You should place the properties in a properties object like so:

```json

{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "geometry": {
        "type": "MultiPolygon",
        "coordinates": [[[
           [-9.5, 41.5],[-1, 41.5],[-1, 44],[-9.5, 44],[-9.5, 41.5]
        ]]]
      },
      "properties":{
        "id": "cantabrican"
      }
    }
  ]
}
```
