### ISSUE TITLE
WMS legenda toont alleen streep en is erg hoog

### ISSUE THREAD

**Issue by rduivenvoorde** [KNMI/adaguc-server#235]
I'm using the following capabilties url to retrieve radar in QGIS:

https://geoservices.knmi.nl/adagucserver?dataset=RADAR&VERSION=1.1.1&request=getcapabilities&SERVICE=WMS&REQUEST=GetCapabilities

In QGIS this gives the following picture when QGIS tries to use the legend image as layer image:

![Screenshot from 2022-11-15 09-21-31](https://user-images.githubusercontent.com/731673/201866988-8815042c-2e3e-4f4c-9a5c-9af60d9ef5cc.png)

Also firing the url in a browser shows this 'strange' legend:

https://geoservices.knmi.nl/adaguc-server?DATASET=RADAR&SERVICE=WMS&&version=1.1.1&service=WMS&request=GetLegendGraphic&layer=RAD_NL25_PCP_CM&format=image/png&STYLE=precip-rainbow/nearest&SLD_VERSION=1.1.0&TRANSPARENT=true

**Comment by maartenplieger** [comment]
Ha thanks for reporting! We will fix this, and let you know.

**Comment by maartenplieger** [comment]
Hi Richard, 

Version 2.7.13 includes a fix for this issue. Can you confirm if this is the case? Thanks again.
