### ISSUE TITLE
Make keep-alive timeout of Adaguc-server configurable 

### ISSUE THREAD

**Issue by PaulVanSchayck** [KNMI/adaguc-server#250]
When deploying Adaguc-Server behind an AWS ELB Appliction LoadBalancer the default keep-alive timeout of gunicorn is too short. This leads to 502 Bad Gateway errors ([docs](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/application-load-balancers.html#connection-idle-timeout)). The solution is to increase the Gunicorn keep-alive timeout to a value longer than the ELB keep-alive timeout. 

The default timeout of gunicorn is 2 seconds ([docs](https://docs.gunicorn.org/en/stable/settings.html#keepalive)). The default keep alive of the AWS ELB is 60 seconds ([docs](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/application-load-balancers.html))

What would be best? Adding an environment variable to the Docker startup script starting gunicorn?

https://github.com/KNMI/adaguc-server/blob/master/Docker/start.sh#L39

**Comment by lukas-phaf** [comment]
Duplicate issue with #317

**Comment by lukas-phaf** [comment]
Duplicate with #317, which is address in #321.

**Comment by lukas-phaf** [comment]
Duplicate with https://github.com/KNMI/adaguc-server/issues/317, which is address in https://github.com/KNMI/adaguc-server/pull/321.
