### ISSUE TITLE
Adaguc-server doesn't like our netCDF files

### ISSUE THREAD

**Issue by David-Gil** [KNMI/adaguc-server#272]
Hi,

I work for the Spanish Weather Service (AEMET).

We've used the docker compose file to create an Adaguc server. We haven't touched any configuration.

We have created netCDF files with cdo from grib1 and grib2 files and placed them in the adaguc-autowms folder. When trying to visualize them, we get this message:
![imagen](https://github.com/KNMI/adaguc-server/assets/1552663/fe7fdc61-f63f-49a3-90ea-e82c98f30f7b)

This information doesn't tell us what is the problem and I haven't found any log message to find out what is preventing us from visualizing the files.

We use the Lambert Conformarl Conic projection. Maybe this is relevant

Some info about the files used:
![imagen](https://github.com/KNMI/adaguc-server/assets/1552663/3af10538-278f-4f7f-80e9-1086c58e8203)
![imagen](https://github.com/KNMI/adaguc-server/assets/1552663/9af17deb-956d-4336-86b3-fe679b7b111b)

We need some way to find out what is preventing us from visualizing the files. Maybe is something about the headers in the netCDF files or the projection. Any hint will be welcome.

Cheers,

David Gil
AEMET

**Comment by ernstdevreede** [comment]
Hello David

I think we have encountered similar problems with cdo generated NetCDF files in the past, but I'm pretty sure the problem is fixable.
You probably could get some more information about the error by looking at the error messages that adaguc-server produces, but that logging might be difficult to access if it is running in the cloud or in docker.

I'm not very familiar with the type of information that cdo sinfo shows.
Could you either add the output of ncdump -h YOURNCFILE or make an example NetCDF available?
I can also have a look at the problem then.

**Comment by David-Gil** [comment]
Hi!,

This is the output of ncdump -h using the netCDF file created from a GRIB1 file:

```
netcdf mbr003_fc2023071312+003_T2m_grb1 {
dimensions:
        time = UNLIMITED ; // (1 currently)
        x = 565 ;
        y = 469 ;
        height = 1 ;
variables:
        double time(time) ;
                time:standard_name = "time" ;
                time:units = "hours since 2023-7-13 12:00:00" ;
                time:calendar = "proleptic_gregorian" ;
                time:axis = "T" ;
        double x(x) ;
                x:standard_name = "projection_x_coordinate" ;
                x:units = "m" ;
                x:axis = "X" ;
        double y(y) ;
                y:standard_name = "projection_y_coordinate" ;
                y:units = "m" ;
                y:axis = "Y" ;
        int Lambert_Conformal ;
                Lambert_Conformal:grid_mapping_name = "lambert_conformal_conic" ;
                Lambert_Conformal:standard_parallel = 40. ;
                Lambert_Conformal:longitude_of_central_meridian = 357.5 ;
                Lambert_Conformal:latitude_of_projection_origin = 40. ;
                Lambert_Conformal:earth_radius = 6367470. ;
                Lambert_Conformal:false_easting = 704556.222658712 ;
                Lambert_Conformal:false_northing = 584635.182097825 ;
                Lambert_Conformal:longitudeOfFirstGridPointInDegrees = -10.165 ;
                Lambert_Conformal:latitudeOfFirstGridPointInDegrees = 34.475 ;
        double height(height) ;
                height:standard_name = "height" ;
                height:long_name = "height" ;
                height:units = "m" ;
                height:positive = "up" ;
                height:axis = "Z" ;
        float var11(time, height, y, x) ;
                var11:table = 2 ;
                var11:grid_mapping = "Lambert_Conformal" ;

// global attributes:
                :CDI = "Climate Data Interface version 2.1.1 (https://mpimet.mpg.de/cdi)" ;
                :Conventions = "CF-1.6" ;
                :history = "Thu Jul 13 20:39:57 2023: cdo -f nc copy ../02_GRIB1_byParam/mbr003_fc2023071312+003_T2m.grb1 ../03_GRIB1_2netCDF/mbr003_fc2023071312+003_T2m_grb1.nc" ;
                :CDO = "Climate Data Operators version 2.1.1 (https://mpimet.mpg.de/cdo)" ;
}
```

And this is the output of ncdump -h of the netCDF file created from a GRIB2 file:
```
netcdf mbr003_fc2023071312+003_T2m_grb2 {
dimensions:
        time = UNLIMITED ; // (1 currently)
        x = 565 ;
        y = 469 ;
        height = 1 ;
variables:
        double time(time) ;
                time:standard_name = "time" ;
                time:units = "hours since 2023-7-13 12:00:00" ;
                time:calendar = "proleptic_gregorian" ;
                time:axis = "T" ;
        double x(x) ;
                x:standard_name = "projection_x_coordinate" ;
                x:units = "m" ;
                x:axis = "X" ;
        double y(y) ;
                y:standard_name = "projection_y_coordinate" ;
                y:units = "m" ;
                y:axis = "Y" ;
        int Lambert_Conformal ;
                Lambert_Conformal:grid_mapping_name = "lambert_conformal_conic" ;
                Lambert_Conformal:standard_parallel = 40. ;
                Lambert_Conformal:longitude_of_central_meridian = 357.5 ;
                Lambert_Conformal:latitude_of_projection_origin = 40. ;
                Lambert_Conformal:earth_radius = 6367470. ;
                Lambert_Conformal:false_easting = 704556.222658712 ;
                Lambert_Conformal:false_northing = 584635.182097825 ;
                Lambert_Conformal:longitudeOfFirstGridPointInDegrees = 349.835 ;
                Lambert_Conformal:latitudeOfFirstGridPointInDegrees = 34.475 ;
        double height(height) ;
                height:standard_name = "height" ;
                height:long_name = "height" ;
                height:units = "m" ;
                height:positive = "up" ;
                height:axis = "Z" ;
        float \2t(time, height, y, x) ;
                \2t:standard_name = "air_temperature" ;
                \2t:long_name = "2 metre temperature" ;
                \2t:units = "K" ;
                \2t:param = "0.0.0" ;
                \2t:grid_mapping = "Lambert_Conformal" ;
                \2t:realization = 3 ;
                \2t:ensemble_members = 10 ;
                \2t:forecast_init_type = 4 ;

// global attributes:
                :CDI = "Climate Data Interface version 2.1.1 (https://mpimet.mpg.de/cdi)" ;
                :Conventions = "CF-1.6" ;
                :history = "Thu Jul 13 20:39:14 2023: cdo -f nc copy ../02_GRIB2_byParam/mbr003_fc2023071312+003_T2m.grb2 ../03_GRIB2_2netCDF/mbr003_fc2023071312+003_T2m_grb2.nc" ;
                :CDO = "Climate Data Operators version 2.1.1 (https://mpimet.mpg.de/cdo)" ;
}
```

Dank je wel!,

David Gil

**Comment by ernstdevreede** [comment]
Hi again,

I beieve we normally require an attribute called "proj4_params" in the projection variable (in your case in the Lambert_Conformal variable). CDO does not add this by itself.
For this file, the proj4_params should be something like:
"+proj=lcc +lat_0=40 +lat_1=40 +lon_0=357.5 +k_0=1.00 +x_0=704556.222658712 +y_0=584635.182097825"

Perhaps you can try to add that information to the Lambert_Conformal variable in an attribute called proj4_params.

It also looks like the NetCDF from the GRIB1 file does not have enough information for ADAGUC to work with.

**Comment by David-Gil** [comment]
Hi,

We have made new netCDF files with the proj4_params variable, but it still doesn't work. Maybe it's not exactly what is expected.

This is the output of ncdump -h:

```
~/adaguc-files/03_GRIB2_2netCDFproj4$ ncdump -h mbr003_fc2023071312+003_T2m_grb2_proj4.nc
netcdf mbr003_fc2023071312+003_T2m_grb2_proj4 {
dimensions:
        time = UNLIMITED ; // (1 currently)
        x = 565 ;
        y = 469 ;
        height = 1 ;
variables:
        double time(time) ;
                time:standard_name = "time" ;
                time:units = "hours since 2023-7-13 12:00:00" ;
                time:calendar = "proleptic_gregorian" ;
                time:axis = "T" ;
        double x(x) ;
                x:standard_name = "projection_x_coordinate" ;
                x:units = "m" ;
                x:axis = "X" ;
        double y(y) ;
                y:standard_name = "projection_y_coordinate" ;
                y:units = "m" ;
                y:axis = "Y" ;
        int Lambert_Conformal ;
                Lambert_Conformal:grid_mapping_name = "lambert_conformal_conic" ;
                Lambert_Conformal:standard_parallel = 40. ;
                Lambert_Conformal:longitude_of_central_meridian = 357.5 ;
                Lambert_Conformal:latitude_of_projection_origin = 40. ;
                Lambert_Conformal:earth_radius = 6367470. ;
                Lambert_Conformal:false_easting = 704556.222658712 ;
                Lambert_Conformal:false_northing = 584635.182097825 ;
                Lambert_Conformal:longitudeOfFirstGridPointInDegrees = 349.835 ;
                Lambert_Conformal:latitudeOfFirstGridPointInDegrees = 34.475 ;
        double height(height) ;
                height:standard_name = "height" ;
                height:long_name = "height" ;
                height:units = "m" ;
                height:positive = "up" ;
                height:axis = "Z" ;
        float \2t(time, height, y, x) ;
                \2t:standard_name = "air_temperature" ;
                \2t:long_name = "2 metre temperature" ;
                \2t:units = "K" ;
                \2t:param = "0.0.0" ;
                \2t:grid_mapping = "Lambert_Conformal" ;
                \2t:realization = 3 ;
                \2t:ensemble_members = 10 ;
                \2t:forecast_init_type = 4 ;
                \2t:proj4_params = "+proj=lcc +lat_0=40 +lat_1=40 +lon_0=357.5 +k_0=1.00 +x_0=704556.222658712 +y_0=584635.182097825" ;

// global attributes:
                :CDI = "Climate Data Interface version 2.1.1 (https://mpimet.mpg.de/cdi)" ;
                :Conventions = "CF-1.6" ;
                :history = "Fri Jul 21 09:42:56 2023: cdo -setattribute,*@proj4_params=+proj=lcc +lat_0=40 +lat_1=40 +lon_0=357.5 +k_0=1.00 +x_0=704556.222658712 +y_0=584635.182097825 /scratch/imp/gSREPS_DEV/gSREPS_ADAGUC/03_GRIB2_2netCDF/mbr003_fc2023071312+003_T2m_grb2.nc /scratch/imp/gSREPS_DEV/gSREPS_ADAGUC/03_GRIB2_2netCDFproj4/mbr003_fc2023071312+003_T2m_grb2_proj4.nc\n",
                        "Fri Jul 21 09:42:56 2023: cdo -f nc copy /scratch/imp/gSREPS_DEV/gSREPS_ADAGUC/02_GRIB2_byParam/mbr003_fc2023071312+003_T2m.grb2 /scratch/imp/gSREPS_DEV/gSREPS_ADAGUC/03_GRIB2_2netCDF/mbr003_fc2023071312+003_T2m_grb2.nc" ;
                :CDO = "Climate Data Operators version 2.1.1 (https://mpimet.mpg.de/cdo)" ;
}
```

**Comment by ernstdevreede** [comment]
Hi David,

On fist glance the NetCDF file lokks fine now.

Do you think you could make the NetCDF file available to me?
I probably can find the problem easier then.

Regards,

Ernst de Vreede

Van: David Gil ***@***.***>
Verzonden: vrijdag 21 juli 2023 12:32
Aan: KNMI/adaguc-server ***@***.***>
CC: Vreede de, Ernst (KNMI) ***@***.***>; Comment ***@***.***>
Onderwerp: Re: [KNMI/adaguc-server] Adaguc-server doesn't like our netCDF files (Issue #272)


Hi,

We have made new netCDF files with the proj4_params variable, but it still doesn't work. Maybe it's not exactly what is expected.

This is the output of ncdump -h:

~/adaguc-files/03_GRIB2_2netCDFproj4$ ncdump -h mbr003_fc2023071312+003_T2m_grb2_proj4.nc

netcdf mbr003_fc2023071312+003_T2m_grb2_proj4 {

dimensions:

        time = UNLIMITED ; // (1 currently)

        x = 565 ;

        y = 469 ;

        height = 1 ;

variables:

        double time(time) ;

                time:standard_name = "time" ;

                time:units = "hours since 2023-7-13 12:00:00" ;

                time:calendar = "proleptic_gregorian" ;

                time:axis = "T" ;

        double x(x) ;

                x:standard_name = "projection_x_coordinate" ;

                x:units = "m" ;

                x:axis = "X" ;

        double y(y) ;

                y:standard_name = "projection_y_coordinate" ;

                y:units = "m" ;

                y:axis = "Y" ;

        int Lambert_Conformal ;

                Lambert_Conformal:grid_mapping_name = "lambert_conformal_conic" ;

                Lambert_Conformal:standard_parallel = 40. ;

                Lambert_Conformal:longitude_of_central_meridian = 357.5 ;

                Lambert_Conformal:latitude_of_projection_origin = 40. ;

                Lambert_Conformal:earth_radius = 6367470. ;

                Lambert_Conformal:false_easting = 704556.222658712 ;

                Lambert_Conformal:false_northing = 584635.182097825 ;

                Lambert_Conformal:longitudeOfFirstGridPointInDegrees = 349.835 ;

                Lambert_Conformal:latitudeOfFirstGridPointInDegrees = 34.475 ;

        double height(height) ;

                height:standard_name = "height" ;

                height:long_name = "height" ;

                height:units = "m" ;

                height:positive = "up" ;

                height:axis = "Z" ;

        float \2t(time, height, y, x) ;

                \2t:standard_name = "air_temperature" ;

                \2t:long_name = "2 metre temperature" ;

                \2t:units = "K" ;

                \2t:param = "0.0.0" ;

                \2t:grid_mapping = "Lambert_Conformal" ;

                \2t:realization = 3 ;

                \2t:ensemble_members = 10 ;

                \2t:forecast_init_type = 4 ;

                \2t:proj4_params = "+proj=lcc +lat_0=40 +lat_1=40 +lon_0=357.5 +k_0=1.00 +x_0=704556.222658712 +y_0=584635.182097825" ;



// global attributes:

                :CDI = "Climate Data Interface version 2.1.1 (https://mpimet.mpg.de/cdi)" ;

                :Conventions = "CF-1.6" ;

                :history = "Fri Jul 21 09:42:56 2023: cdo ***@***.***_params=+proj=lcc +lat_0=40 +lat_1=40 +lon_0=357.5 +k_0=1.00 +x_0=704556.222658712 +y_0=584635.182097825 /scratch/imp/gSREPS_DEV/gSREPS_ADAGUC/03_GRIB2_2netCDF/mbr003_fc2023071312+003_T2m_grb2.nc /scratch/imp/gSREPS_DEV/gSREPS_ADAGUC/03_GRIB2_2netCDFproj4/mbr003_fc2023071312+003_T2m_grb2_proj4.nc\n",

                        "Fri Jul 21 09:42:56 2023: cdo -f nc copy /scratch/imp/gSREPS_DEV/gSREPS_ADAGUC/02_GRIB2_byParam/mbr003_fc2023071312+003_T2m.grb2 /scratch/imp/gSREPS_DEV/gSREPS_ADAGUC/03_GRIB2_2netCDF/mbr003_fc2023071312+003_T2m_grb2.nc" ;

                :CDO = "Climate Data Operators version 2.1.1 (https://mpimet.mpg.de/cdo)" ;

}

**Comment by David-Gil** [comment]
Hi,

Let's see if these links work well:

- https://drive.google.com/file/d/1DKjrwcyfu4XG2uP9UVlfImlGX5eSmm6M/view?usp=drive_link
- https://drive.google.com/file/d/1IcmKN_i2zrc-4r7XL6nUyKK-EP4JzL3C/view?usp=drive_link
- https://drive.google.com/file/d/1iXxtFKzct5X-QcPjjT_fv1mtcNixkmeN/view?usp=drive_link

Permissions are given for download, but if it asks for permission, I'll give it to you as soon as I can.

Cheers,

David Gil

**Comment by David-Gil** [comment]
We finally found out why our files didn't work. The names of our files contain the character '+'. Adaguc interprets this character as a space and then the path as invalid.

The logs of the adaguc server can be accessed from outside the container with

```bash
docker logs -f my-adaguc-server
```

That gave us the information about the invalid path and the conflicting character.

Without that character, the files work as expected.

Thank you so much for your time. I'll close this issue with this comment and I'll open another one explaining the problem with the conflicting character for future users (and perhaps it can be fixed, although I can imagine the character '+' can cause a number of issues in the URL).

Cheers! (en nogmaals dank je wel voor jouw tijd)

David Gil

**Comment by ernstdevreede** [comment]
Hi David,

It's good you can go on.

I would think there are more instances where filenames contain a plus sign (like many CMIP5/6 files), so I'm a bit surprised this doesn't work.
We would appreciate it if you could make issue on GitHub for this, so we don't forget to fix it soon.

Regards, Ernst

Op 26 jul. 2023 10:21 schreef David Gil ***@***.***>:

We finally found out why our files didn't work. The names of our files contain the character '+'. Adaguc interprets this character as a space and then the path as invalid.

The logs of the adaguc server can be accessed from outside the container with

docker logs -f my-adaguc-server

That gave us the information about the invalid path and the conflicting character.

Without that character, the files work as expected.

Thank you so much for your time. I'll close this issue with this comment and I'll open another one explaining the problem with the conflicting character for future users (and perhaps it can be fixed, although I can imagine the character '+' can cause a number of issues in the URL).

Cheers! (en nogmaals dank je wel voor jouw tijd)

David Gil
