### ISSUE TITLE
Plus sign in file name gives invalid path

### ISSUE THREAD

**Issue by David-Gil** [KNMI/adaguc-server#273]
Hi!,

Our netCDF files have these file names:
* mbr003_fc2023071312+003_UV10m_grb2_proj4nco.nc
* mbr003_fc2023071312+003_RH2m_grb2_proj4nco.nc
* mbr003_fc2023071312+003_T2m_grb2_proj4nco.nc

When trying to visualize these files placed in adaguc-autowms, ADAGUC gives this message in the browser:
![imagen](https://github.com/KNMI/adaguc-server/assets/1552663/524fb9b7-da76-447d-a43b-a42791538243)

The text in the URL has the  %2B correctly decoded (it is the '+' sign).
```
Unable to get WMS GetCapabilities[http://172.24.139.98/adagucserver?source=03_GRIB2_2netCDFproj4nco%2Fmbr003_fc2023071312%2B003_RH2m_grb2_proj4nco.nc&]
```

On the other hand, the logs give this text:

```
applicationlog 2023-07-26 10:28:23,151 - routers.wmswcs - INFO - [D:000:pid723: adagucserverEC/CServerParams.cpp:388 CServerParams]              2023-07-26T10:28:23Z LOCALFILEACCESS: Invalid path '/data/adaguc-autowms//03_GRIB2_2netCDFproj4nco/mbr003_fc2023071312 003_RH2m_grb2_proj4nco.nc'
[D:001:pid723: adagucserverEC/CServerParams.cpp:388 CServerParams]              2023-07-26T10:28:23Z LOCALFILEACCESS: Invalid path '/data/adaguc-data//03_GRIB2_2netCDFproj4nco/mbr003_fc2023071312 003_RH2m_grb2_proj4nco.nc'
[D:002:pid723: adagucserverEC/CAutoResource.cpp:213 CAutoResource]              2023-07-26T10:28:23Z Unable to resolve path for autoresource file 03_GRIB2_2netCDFproj4nco/mbr003_fc2023071312 003_RH2m_grb2_proj4nco.nc
[D:003:pid723: adagucserverEC/CAutoResource.cpp:214 CAutoResource]              2023-07-26T10:28:23Z Please note that only absolute paths without symbolic links can be used
[E:004:pid723: adagucserverEC/CRequest.cpp:2961 CRequest]                       2023-07-26T10:28:23Z AutoResource failed
applicationlog 2023-07-26 10:28:23,152 - routers.wmswcs - INFO - Adaguc status code was 1
172.20.0.4:50300 - "GET /wms?source=03_GRIB2_2netCDFproj4nco%2Fmbr003_fc2023071312%2B003_RH2m_grb2_proj4nco.nc&&service=WMS&request=GetCapabilities&random0.12704694024335694 HTTP/1.0" 500
```
The '+' has been replaced somewhere by a space, which gives an invalid path.

When the '+' is changed in the file name to another character, the problem disappears.

The double slash between adaguc-autowms and the subfolder is also somewhat suspiciuos, although it probably won't have any consequence.

Cheers,

David Gil

**Comment by maartenplieger** [comment]
Thanks for reporting David! We will let you know when we have solved this.

**Comment by maartenplieger** [comment]
Can you check if the latest version https://github.com/KNMI/adaguc-server/releases/tag/2.11.2 resolves your issue?

**Comment by David-Gil** [comment]
The problem has disappeared.

Thank you so much!

David Gil and the gSREPS Predictability Group (AEMET)
