### ISSUE TITLE
Make gunicorn keepalive time configurable to prevent HTTP 502 gateway errors behind load balancer

### ISSUE THREAD

**Issue by PaulVanSchayck** [KNMI/adaguc-server#317]
When using gunicorn behind a load balancer, the default gunicorn HTTP keep-alive timeout is set too low.

The [default gunicorn Keepalive timeout](https://docs.gunicorn.org/en/stable/settings.html) is 2 seconds. And the [default AWS ALB and ELB Keep-alive timeout](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/application-load-balancers.html#connection-idle-timeout) is 60 seconds. This can lead to HTTP 502 gateway errors on the ALB. The reason why is explained [here](https://iximiuz.com/en/posts/reverse-proxy-http-keep-alive-and-502s/). These HTTP 502 errors can be observed in the monitoring of the load balancer. 

In the KNMI Adaguc Nested stack configuration, the Keep alive timeout is set to 180 seconds. This would mean that gunicorn `--keepalive` needs to be set to more than that. The exact values could be discussed further, and also if the value set for Gunicorn needs to be configurable.

**Comment by lukas-phaf** [comment]
Merged and released.
