### ISSUE TITLE
Default time referenced to forecast_reference_time

### ISSUE THREAD

**Issue by lllliso** [KNMI/adaguc-server#403]
When loading a dataset with dimensions: time and  forecast_reference_time:
1. When the "default" key time is  "min" it displays the first time of the first forecast_reference_time.
2. When the "default" key time is  "max" it displays the last time of the last forecast_reference_time.

We would like a default key time value such it displays the first time of the last (or default) forecast_reference_time.

The xml would perhaps look like in the comment bellow 

Cheers

**Comment by lllliso** [comment]
"<Dimension name="time" interval="PT15M" default="2024-09-05T08:45:00Z" >time</Dimension>"
"<Dimension name="forecast_reference_time" default="max" >forecast_reference_time</Dimension>"

**Comment by lllliso** [comment]
Dimension name="time" interval="PT15M" default="forecast_reference_time" time  /Dimension
Dimension name="forecast_reference_time" default="max" forecast_reference_time /Dimension

**Comment by maartenplieger** [comment]
Hey Llorenc!

Good request. We need something similar. We are working on it. See https://github.com/KNMI/adaguc-server/pull/421

**Comment by maartenplieger** [comment]
As written in the documentation, you can now use `forecast_reference_time+PT1H` in the dimension.
