### ISSUE TITLE
Create a wiki and pull the wiki from https://github.com/saskiawagenaar/adaguc-server.wiki.git

### ISSUE THREAD

**Issue by saskiawagenaar** [KNMI/adaguc-server#52]
On my fork I have created a wiki in which I describe how to build and deploy the adaguc-server gitbook.

In order to obtain this wiki in the original adaguc-server, the following steps should be followed:

1. Create a wiki in the adaguc-server KNMI repo
2. Clone the adaguc-server wiki repo and merge the repo from the fork:
```
$ git clone https://github.com/KNMI/adaguc-server.wiki.git
$ cd adaguc-server.wiki.git
$ git pull https://github.com/saskiawagenaar/adaguc-server.wiki.git master
$ git push origin master
```

**Comment by maartenplieger** [comment]
Thanks! Merged repositories.
