### ISSUE TITLE
Replace use of exceptions for non-exceptional cases with proper control flow

### ISSUE THREAD

**Issue by mtsr** [KNMI/adaguc-server#62]
Exceptions are meant for exceptional situations, not regular control flow. They also tend to be much slower than proper control flow.

See e.g. https://stackoverflow.com/questions/13835817/are-exceptions-in-c-really-slow

Particularly visible case is CCDFVariable->getAttribute()

**Comment by maartenplieger** [comment]
Good idea, but it was built in from the start. It is too much work to change afterwards. Lets keep this in mind for future improvements.
