### ISSUE TITLE
adaguc-server-updatedatasets.sh command line option parsing not extendable

### ISSUE THREAD

**Issue by neutvd** [KNMI/adaguc-server#71]
Because the script relies on positional arguments and tests for a second argument if there is a first argument detected it is impossible to add command line arguments independent of the first command line argument.

I'm expecting there are currently other scripts dependent on this interface, so my current patch in pull request #70 doesn't introduce any backwards compatibility (hopefully) by using an environment variable, but I had to deal with the deletion of servicehealth files.

It would help if the command line argument parsing were refactored using the getopts bash function so that command line arguments can be added independent of already existing ones. Let me know if you want me to make a new pull request for this. For now please merge #70.

**Comment by maartenplieger** [comment]
This is now available via https://github.com/KNMI/adaguc-server/blob/master/Docker/adaguc-server-addfile.sh

Thanks!
