### ISSUE TITLE
TROPOMI NetCDF files give a warning

### ISSUE THREAD

**Issue by neutvd** [KNMI/adaguc-server#76]
``
[W: CCDFNetCDFIO.cpp, 620 in NetCDFReader]                         Warning unknown attribute type 10
[W: CCDFNetCDFIO.cpp, 425 in NetCDFReader]                         Unknown attribute type for attribute time_reference_seconds_since_1970 10 11 0
``
Apparently newer NetCDF library version introduced a new attribute type that is being used by TROPOMI files and not yet supported by adaguc-server?

**Comment by maartenplieger** [comment]
It seems this is fixed
